# Generated by Django 5.1.3 on 2024-12-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v2', '0002_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AlterField(
            model_name='score',
            name='team',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='temaname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
