# Generated by Django 5.1.3 on 2024-12-03 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v2', '0003_delete_game_alter_score_team_alter_team_temaname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_v2.team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_v2.team'),
        ),
    ]
