# Generated by Django 5.1.3 on 2024-12-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v2', '0004_alter_score_team_alter_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
