# Generated by Django 5.1.3 on 2025-04-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v2', '0006_alter_user_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
