# Generated by Django 5.1.3 on 2025-04-29 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v2', '0007_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
                ('point', models.IntegerField(default=10)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_v2.quiz')),
            ],
        ),
    ]
