# Generated by Django 5.1.3 on 2025-04-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v2', '0009_leader_remove_user_team_user_leader_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leader',
            name='leadername',
            field=models.CharField(max_length=100),
        ),
    ]
