# Generated by Django 5.1.3 on 2025-05-05 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v2', '0010_leader_order_alter_leader_leadername'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='subquiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='app_v2.subquiz'),
        ),
    ]
